meta-xilinx: fix layer dependency errors while doing yocto-check-layer
Issue: LINCD-2561

There are layer dependencies as below:
opencv (in meta-xilinx-bsp) depends on libeigen (in meta-openembedded/meta-oe)
python3-pynq (in meta-xilinx-pynq) depends on python3-cffi (in meta-openembedded/meta-python)

We need explictly add these relevant layers to LAYERDEPENDS, or else the script
yocto-check-layer will report the error:

ERROR: Nothing PROVIDES 'libeigen' (but layers/meta-xilinx/meta-xilinx-bsp/recipes-support/opencv/opencv_3.4.3.bb DEPENDS on or otherwise requires it). Close matches:
libevent
libice
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>