meta-xilinx-bsp: fix DEPENDS error for gstreamer1.0-plugins-base package
Issue: LINCD-4562

In some scenario, gstreamer1.0-plugins-base would be built without
opengl or vulkan support (wrlinux-cgl distro), and without opengl
or vlukan, mesa can't be built. So we add a new variable
DEPENDS_MESA_XLNX to adapt this case, or else there would be error
info as below:

ERROR: Nothing PROVIDES 'mesa' (but layers/oe-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.18.3.bb DEPENDS on or otherwise requires it)
mesa was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>