cairo: add trace to PACKAGECONFIG to fix do_package error while enabling multilib
Issue: LINCD-2643

In cairo_1.16.0.bb, the macro MULTILIB_SCRIPTS is set to be
"${PN}-perf-utils:${bindir}/cairo-trace" which indicates that the
script cairo-trace will be handled using update-alternatives with multilib.
But in the bbappend meta-xilinx-bsp/recipes-graphics/cairo/cairo_%.bbappend,
the "trace" is removed from PACKAGECONFIG and this will cause that the class
multilib_script can't find the cairo-trace script. The error log is as below:

ERROR: cairo-1.16.0-r0 do_package: Error executing a python function in exec_python_func() autogenerated:
......
Exception: bb.process.ExecutionError: Execution of 'build/tmp-glibc/work/cortexa53-wrs-linux/cairo/1.16.0-r0/temp/run.multilibscript_rename.22582' failed with exit code 1:
mv: cannot stat 'build/tmp-glibc/work/cortexa53-wrs-linux/cairo/1.16.0-r0/package/usr/bin/cairo-trace': No such file or directory
WARNING: exit code 1 from a shell command.

So add "trace" back to PACKAGECONFIG to fix the do_package error.

Upstream-Status: Submitted [https://lists.yoctoproject.org/g/meta-xilinx/message/4722]

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>